// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function ScanCmsPath(arg1) {
  return window['go']['main']['App']['ScanCmsPath'](arg1);
}

export function UnzipFile(arg1) {
  return window['go']['main']['App']['UnzipFile'](arg1);
}
