// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function Greet(arg1:string):Promise<string>;

export function OpenDirectory():Promise<string>;

export function ScanCmsPath(arg1:string):Promise<string>;

export function UnzipFile(arg1:dto.FileData):Promise<void>;
